---
name: App-Siesh
version: 0.11
author:
  - 'Mario Domgoergen <dom@math.uni-bonn.de>'
abstract: interactive sieve shell
license: perl
resources:
  license: ~
  repository: http://github.com/mdom/app-siesh
requires:
  Config::Find: 0
  File::Temp: 0
  IO::Prompt: 0
  IO::Socket::SSL: 0
  Net::ManageSieve: 0
  Pod::Usage: 0
  Term::ShellUI: 0
  parent: 0
build_requires:
  Test::More: 0
provides:
  App::Siesh:
    file: lib/App/Siesh.pm
    version: 0.11
  Net::ManageSieve::Siesh:
    file: lib/Net/ManageSieve/Siesh.pm
    version: 0.05
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
