---
name: App-Siesh
version: 0.20
author:
  - 'Mario Domgoergen <dom@math.uni-bonn.de>'
abstract: interactive sieve shell
license: perl
resources:
  license: ~
  repository: http://github.com/mdom/app-siesh
requires:
  Config::Find: 0
  Config::Tiny: 0
  File::Temp: 0
  Getopt::Long: 0
  IO::File: 0
  IO::Handle: 0
  IO::Interactive: 0
  IO::Prompt: 0
  IO::Socket::SSL: 0
  IPC::System::Simple: 0
  Net::ManageSieve: 0
  Pod::Usage: 0
  Term::ShellUI: 0
  autodie: 0
  parent: 0
build_requires:
  IO::String: 0
  Test::More: 0
  Test::Output: 0
recommends:
  Authen::SASL: 0
provides:
  App::Siesh:
    file: lib/App/Siesh.pm
    version: 0.20
  App::Siesh::Batch:
    file: lib/App/Siesh/Batch.pm
  Net::ManageSieve::Siesh:
    file: lib/Net/ManageSieve/Siesh.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
